#!/usr/bin/env ruby

VERSION = '1.1.10'
ROOT_DIR = `ls -l /usr/bin/`.split("\n").detect{|symlink| symlink.include? 'git-hotfix' }.scan(/\->\s(.*)\/hf/)[0][0]
PROJECT_DIR = `pwd`.gsub("\n", '')

# p ROOT_DIR
# p PROJECT_DIR

require 'yaml'
require ROOT_DIR + '/context.rb'
require ROOT_DIR + '/config.rb'
require ROOT_DIR + '/remote.rb'
require ROOT_DIR + '/exec_cli.rb'
require ROOT_DIR + '/deploy_action.rb'
require ROOT_DIR + '/save_action.rb'
require ROOT_DIR + '/checkout_action.rb'
require ROOT_DIR + '/delete_merged_action.rb'
require ROOT_DIR + '/config_action.rb'
require ROOT_DIR + '/sync_action.rb'
require ROOT_DIR + '/actions/reset_action.rb'
require ROOT_DIR + '/actions/get_action.rb'
require ROOT_DIR + '/actions/st_action.rb'

def help_action
  print "Version: #{VERSION}" + "\n\n"
  print 'Examples: ' + "\n\n"
  print 'hf 777' + "\n"
  print 'hf save "its a comment"' + "\n"
  print 'hf save master develop "its a comment"' + "\n"
  print 'hf deploy master develop "its a comment"' + "\n"
  print 'hf delete-merged' + "\n"
  print 'hf config' + "\n"
  print 'hf self-update [VERSION]' + "\n"
  print 'hf sync' + "\n"
  print 'hf reset' + "\n"
  print 'hf get' + "\n"
  print 'hf st' + "\n"
  print "\n"
  print 'Options: ' + "\n"
  print 'No push: (--no-push|--local) prevents pushes to remote' + "\n"
  print 'hf save master "its a comment" --local' + "\n"
  print "\n"
end

def run_actions
  args = ARGV.select{|arg| arg[0] != '-' || arg.include?(' ') }
  flags = ARGV.select{|arg| arg[0] == '-' && !arg.include?(' ') }
  options = {}
  options[:no_push] = flags.include?('--no-push') || flags.include?('--local')
  options[:always_commit] = flags.include?('--ac') || flags.include?('--always-commit')

  return SaveAction.(args, options) if args[0] == 'save'
  return DeployAction.(args, options) if args[0] == 'deploy'
  return ConfigAction.(args, options) if args[0] == 'config'
  return SyncAction.(args, options) if args[0] == 'sync'
  return DeleteMergedAction.(args, options) if args[0] == 'delete-merged'
  return ResetAction.(args, options) if args[0] == 'reset'
  return GetAction.(args, options) if args[0] == 'get'
  return StAction.(args, options) if args[0] == 'st'

  if args[0] == 'self-update'
    self_update_action
    exit
  end

  return CheckoutAction.(args, options) if args.count == 1

  if args.count == 0
    help_action
    exit
  end
end

def self_update_action
  checkout = ARGV[1] || :master
  dir = `ls -l /usr/bin/`.split("\n").detect{|symlink| symlink.include? 'git-hotfix' }
  dir = dir.scan(/\->\s(.*)\/hf/)[0][0]
  `cd #{dir} && git checkout #{checkout} && git pull origin #{checkout}`
end

def main
  ExecCli.(run_actions)
end

main()
